In [1]:
import json
import pandas as pd

with open('new_city_inspections.json', 'r', encoding='utf-8') as file:
    data = json.load(file)
    
df = pd.DataFrame(data)

In [2]:
df

,_id,id,certificate_number,business_name,date,result,sector,address
0,{'$oid': '56d61033a378eccde8a8354f'},10021-2015-ENFO,9278806,ATLIXCO DELI GROCERY INC.,Feb 20 2015,No Violation Issued,Cigarette Retail Dealer - 127,"{'city': 'RIDGEWOOD', 'zip': 11385, 'street': ..."
1,{'$oid': '56d61033a378eccde8a83550'},10057-2015-ENFO,6007104,LD BUSINESS SOLUTIONS,Feb 25 2015,Violation Issued,Tax Preparers - 891,"{'city': 'NEW YORK', 'zip': 10030, 'street': '..."
2,{'$oid': '56d61033a378eccde8a83551'},10084-2015-ENFO,9278914,MICHAEL GOMEZ RANGHALL,Feb 10 2015,No Violation Issued,Locksmith - 062,"{'city': 'QUEENS VLG', 'zip': 11427, 'street':..."
3,{'$oid': '56d61033a378eccde8a83552'},1012-2015-CMPL,5346909,A&C CHIMNEY CORP.,Apr 22 2015,Violation Issued,Home Improvement Contractor - 100,"{'city': 'QUEENS VLG', 'zip': 11428, 'street':..."
4,{'$oid': '56d61033a378eccde8a83553'},10127-2015-CMPL,5381180,ERIC CONSTRUCTION AND DECORATING INC.,Sep 8 2015,Violation Issued,Home Improvement Contractor - 100,"{'city': 'STATEN ISLAND', 'zip': 10304, 'stree..."
...,...,...,...,...,...,...,...,...
81042,{'$oid': '56d61035a378eccde8a971e1'},5821-2016-ENFO,5391052,"SHARON, JOSEPH",Jan 20 2016,Violation Issued,Stoop Line Stand - 033,"{'city': 'BROOKLYN', 'zip': 11235, 'street': '..."
81043,{'$oid': '56d61035a378eccde8a971e2'},5543-2016-ENFO,9324981,TWO BROTHERS FASHION LTD,Jan 20 2016,No Violation Issued,Misc Non-Food Retail - 817,"{'city': 'JACKSON HEIGHTS', 'zip': 11372, 'str..."
81044,{'$oid': '56d61035a378eccde8a971e3'},10192-2016-ENFO,5393182,"PIEROTTI, ESTEBAN A.",Dec 16 2015,Violation Issued,Pedicab Business - 130,"{'city': 'NEW YORK', 'zip': 10019, 'street': '..."
81045,{'$oid': '56d61035a378eccde8a971e4'},4982-2016-ENFO,50066535,"SOHO GARDEN, INC.",Jan 22 2016,No Violation Issued,Cigarette Retail Dealer - 127,"{'city': 'NEW YORK', 'zip': 10012, 'street': '..."
81046,{'$oid': '56d61035a378eccde8a971e5'},4413-2016-ENFO,9314366,"NINE & ONE GROCERY, INC.",Jan 21 2016,No Violation Issued,Tobacco Prod'T Sales - 890,"{'city': 'BROOKLYN', 'zip': 11221, 'street': '..."

In [3]:
df.dtypes

_id                   object
id                    object
certificate_number    object
business_name         object
date                  object
result                object
sector                object
address               object
dtype: object

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
df

,_id,id,certificate_number,business_name,date,result,sector,address
0,{'$oid': '56d61033a378eccde8a8354f'},10021-2015-ENFO,9278806,ATLIXCO DELI GROCERY INC.,2015-02-20,No Violation Issued,Cigarette Retail Dealer - 127,"{'city': 'RIDGEWOOD', 'zip': 11385, 'street': ..."
1,{'$oid': '56d61033a378eccde8a83550'},10057-2015-ENFO,6007104,LD BUSINESS SOLUTIONS,2015-02-25,Violation Issued,Tax Preparers - 891,"{'city': 'NEW YORK', 'zip': 10030, 'street': '..."
2,{'$oid': '56d61033a378eccde8a83551'},10084-2015-ENFO,9278914,MICHAEL GOMEZ RANGHALL,2015-02-10,No Violation Issued,Locksmith - 062,"{'city': 'QUEENS VLG', 'zip': 11427, 'street':..."
3,{'$oid': '56d61033a378eccde8a83552'},1012-2015-CMPL,5346909,A&C CHIMNEY CORP.,2015-04-22,Violation Issued,Home Improvement Contractor - 100,"{'city': 'QUEENS VLG', 'zip': 11428, 'street':..."
4,{'$oid': '56d61033a378eccde8a83553'},10127-2015-CMPL,5381180,ERIC CONSTRUCTION AND DECORATING INC.,2015-09-08,Violation Issued,Home Improvement Contractor - 100,"{'city': 'STATEN ISLAND', 'zip': 10304, 'stree..."
...,...,...,...,...,...,...,...,...
81042,{'$oid': '56d61035a378eccde8a971e1'},5821-2016-ENFO,5391052,"SHARON, JOSEPH",2016-01-20,Violation Issued,Stoop Line Stand - 033,"{'city': 'BROOKLYN', 'zip': 11235, 'street': '..."
81043,{'$oid': '56d61035a378eccde8a971e2'},5543-2016-ENFO,9324981,TWO BROTHERS FASHION LTD,2016-01-20,No Violation Issued,Misc Non-Food Retail - 817,"{'city': 'JACKSON HEIGHTS', 'zip': 11372, 'str..."
81044,{'$oid': '56d61035a378eccde8a971e3'},10192-2016-ENFO,5393182,"PIEROTTI, ESTEBAN A.",2015-12-16,Violation Issued,Pedicab Business - 130,"{'city': 'NEW YORK', 'zip': 10019, 'street': '..."
81045,{'$oid': '56d61035a378eccde8a971e4'},4982-2016-ENFO,50066535,"SOHO GARDEN, INC.",2016-01-22,No Violation Issued,Cigarette Retail Dealer - 127,"{'city': 'NEW YORK', 'zip': 10012, 'street': '..."
81046,{'$oid': '56d61035a378eccde8a971e5'},4413-2016-ENFO,9314366,"NINE & ONE GROCERY, INC.",2016-01-21,No Violation Issued,Tobacco Prod'T Sales - 890,"{'city': 'BROOKLYN', 'zip': 11221, 'street': '..."

In [6]:
df['date'].dtypes

dtype('<M8[ns]')

In [7]:
df[['id1', 'id2', 'id']] = df['id'].str.split(pat = '-', expand=True)

In [8]:
df

,_id,id,certificate_number,business_name,date,result,sector,address,id1,id2
0,{'$oid': '56d61033a378eccde8a8354f'},ENFO,9278806,ATLIXCO DELI GROCERY INC.,2015-02-20,No Violation Issued,Cigarette Retail Dealer - 127,"{'city': 'RIDGEWOOD', 'zip': 11385, 'street': ...",10021,2015
1,{'$oid': '56d61033a378eccde8a83550'},ENFO,6007104,LD BUSINESS SOLUTIONS,2015-02-25,Violation Issued,Tax Preparers - 891,"{'city': 'NEW YORK', 'zip': 10030, 'street': '...",10057,2015
2,{'$oid': '56d61033a378eccde8a83551'},ENFO,9278914,MICHAEL GOMEZ RANGHALL,2015-02-10,No Violation Issued,Locksmith - 062,"{'city': 'QUEENS VLG', 'zip': 11427, 'street':...",10084,2015
3,{'$oid': '56d61033a378eccde8a83552'},CMPL,5346909,A&C CHIMNEY CORP.,2015-04-22,Violation Issued,Home Improvement Contractor - 100,"{'city': 'QUEENS VLG', 'zip': 11428, 'street':...",1012,2015
4,{'$oid': '56d61033a378eccde8a83553'},CMPL,5381180,ERIC CONSTRUCTION AND DECORATING INC.,2015-09-08,Violation Issued,Home Improvement Contractor - 100,"{'city': 'STATEN ISLAND', 'zip': 10304, 'stree...",10127,2015
...,...,...,...,...,...,...,...,...,...,...
81042,{'$oid': '56d61035a378eccde8a971e1'},ENFO,5391052,"SHARON, JOSEPH",2016-01-20,Violation Issued,Stoop Line Stand - 033,"{'city': 'BROOKLYN', 'zip': 11235, 'street': '...",5821,2016
81043,{'$oid': '56d61035a378eccde8a971e2'},ENFO,9324981,TWO BROTHERS FASHION LTD,2016-01-20,No Violation Issued,Misc Non-Food Retail - 817,"{'city': 'JACKSON HEIGHTS', 'zip': 11372, 'str...",5543,2016
81044,{'$oid': '56d61035a378eccde8a971e3'},ENFO,5393182,"PIEROTTI, ESTEBAN A.",2015-12-16,Violation Issued,Pedicab Business - 130,"{'city': 'NEW YORK', 'zip': 10019, 'street': '...",10192,2016
81045,{'$oid': '56d61035a378eccde8a971e4'},ENFO,50066535,"SOHO GARDEN, INC.",2016-01-22,No Violation Issued,Cigarette Retail Dealer - 127,"{'city': 'NEW YORK', 'zip': 10012, 'street': '...",4982,2016
81046,{'$oid': '56d61035a378eccde8a971e5'},ENFO,9314366,"NINE & ONE GROCERY, INC.",2016-01-21,No Violation Issued,Tobacco Prod'T Sales - 890,"{'city': 'BROOKLYN', 'zip': 11221, 'street': '...",4413,2016

In [9]:
new_address = []
for item in df['address']:
    address_item = {
        'city': item['city'],
        'zip': item['zip'],
        'street': item['street'],
        'number': item['number']
    }
    new_address.append(address_item)

In [10]:
af = pd.DataFrame(new_address)

In [11]:
af

                  city    zip                   street number
0            RIDGEWOOD  11385               MENAHAN ST   1712
1             NEW YORK  10030  FREDERICK DOUGLASS BLVD   2655
2           QUEENS VLG  11427                 214TH ST   8823
3           QUEENS VLG  11428                 210TH ST   9440
4        STATEN ISLAND  10304             TODT HILL RD   1233
...                ...    ...                      ...    ...
81042         BROOKLYN  11235       BRIGHTON BEACH AVE   1023
81043  JACKSON HEIGHTS  11372            ROOSEVELT AVE   8503
81044         NEW YORK  10019         WEST   59 STREET
81045         NEW YORK  10012                PRINCE ST     40
81046         BROOKLYN  11221        KNICKERBOCKER AVE    686

[81047 rows x 4 columns]

In [12]:
df = pd.concat([df, af], axis=1)

In [13]:
df

,_id,id,certificate_number,business_name,date,result,sector,address,id1,id2,city,zip,street,number
0,{'$oid': '56d61033a378eccde8a8354f'},ENFO,9278806,ATLIXCO DELI GROCERY INC.,2015-02-20,No Violation Issued,Cigarette Retail Dealer - 127,"{'city': 'RIDGEWOOD', 'zip': 11385, 'street': ...",10021,2015,RIDGEWOOD,11385,MENAHAN ST,1712
1,{'$oid': '56d61033a378eccde8a83550'},ENFO,6007104,LD BUSINESS SOLUTIONS,2015-02-25,Violation Issued,Tax Preparers - 891,"{'city': 'NEW YORK', 'zip': 10030, 'street': '...",10057,2015,NEW YORK,10030,FREDERICK DOUGLASS BLVD,2655
2,{'$oid': '56d61033a378eccde8a83551'},ENFO,9278914,MICHAEL GOMEZ RANGHALL,2015-02-10,No Violation Issued,Locksmith - 062,"{'city': 'QUEENS VLG', 'zip': 11427, 'street':...",10084,2015,QUEENS VLG,11427,214TH ST,8823
3,{'$oid': '56d61033a378eccde8a83552'},CMPL,5346909,A&C CHIMNEY CORP.,2015-04-22,Violation Issued,Home Improvement Contractor - 100,"{'city': 'QUEENS VLG', 'zip': 11428, 'street':...",1012,2015,QUEENS VLG,11428,210TH ST,9440
4,{'$oid': '56d61033a378eccde8a83553'},CMPL,5381180,ERIC CONSTRUCTION AND DECORATING INC.,2015-09-08,Violation Issued,Home Improvement Contractor - 100,"{'city': 'STATEN ISLAND', 'zip': 10304, 'stree...",10127,2015,STATEN ISLAND,10304,TODT HILL RD,1233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81042,{'$oid': '56d61035a378eccde8a971e1'},ENFO,5391052,"SHARON, JOSEPH",2016-01-20,Violation Issued,Stoop Line Stand - 033,"{'city': 'BROOKLYN', 'zip': 11235, 'street': '...",5821,2016,BROOKLYN,11235,BRIGHTON BEACH AVE,1023
81043,{'$oid': '56d61035a378eccde8a971e2'},ENFO,9324981,TWO BROTHERS FASHION LTD,2016-01-20,No Violation Issued,Misc Non-Food Retail - 817,"{'city': 'JACKSON HEIGHTS', 'zip': 11372, 'str...",5543,2016,JACKSON HEIGHTS,11372,ROOSEVELT AVE,8503
81044,{'$oid': '56d61035a378eccde8a971e3'},ENFO,5393182,"PIEROTTI, ESTEBAN A.",2015-12-16,Violation Issued,Pedicab Business - 130,"{'city': 'NEW YORK', 'zip': 10019, 'street': '...",10192,2016,NEW YORK,10019,WEST 59 STREET,
81045,{'$oid': '56d61035a378eccde8a971e4'},ENFO,50066535,"SOHO GARDEN, INC.",2016-01-22,No Violation Issued,Cigarette Retail Dealer - 127,"{'city': 'NEW YORK', 'zip': 10012, 'street': '...",4982,2016,NEW YORK,10012,PRINCE ST,40
81046,{'$oid': '56d61035a378eccde8a971e5'},ENFO,9314366,"NINE & ONE GROCERY, INC.",2016-01-21,No Violation Issued,Tobacco Prod'T Sales - 890,"{'city': 'BROOKLYN', 'zip': 11221, 'street': '...",4413,2016,BROOKLYN,11221,KNICKERBOCKER AVE,686

In [14]:
df = df.drop(['_id','id1','id2','address','zip','street','number'], axis=1)
df

,id,certificate_number,business_name,date,result,sector,city
0,ENFO,9278806,ATLIXCO DELI GROCERY INC.,2015-02-20,No Violation Issued,Cigarette Retail Dealer - 127,RIDGEWOOD
1,ENFO,6007104,LD BUSINESS SOLUTIONS,2015-02-25,Violation Issued,Tax Preparers - 891,NEW YORK
2,ENFO,9278914,MICHAEL GOMEZ RANGHALL,2015-02-10,No Violation Issued,Locksmith - 062,QUEENS VLG
3,CMPL,5346909,A&C CHIMNEY CORP.,2015-04-22,Violation Issued,Home Improvement Contractor - 100,QUEENS VLG
4,CMPL,5381180,ERIC CONSTRUCTION AND DECORATING INC.,2015-09-08,Violation Issued,Home Improvement Contractor - 100,STATEN ISLAND
...,...,...,...,...,...,...,...
81042,ENFO,5391052,"SHARON, JOSEPH",2016-01-20,Violation Issued,Stoop Line Stand - 033,BROOKLYN
81043,ENFO,9324981,TWO BROTHERS FASHION LTD,2016-01-20,No Violation Issued,Misc Non-Food Retail - 817,JACKSON HEIGHTS
81044,ENFO,5393182,"PIEROTTI, ESTEBAN A.",2015-12-16,Violation Issued,Pedicab Business - 130,NEW YORK
81045,ENFO,50066535,"SOHO GARDEN, INC.",2016-01-22,No Violation Issued,Cigarette Retail Dealer - 127,NEW YORK
81046,ENFO,9314366,"NINE & ONE GROCERY, INC.",2016-01-21,No Violation Issued,Tobacco Prod'T Sales - 890,BROOKLYN

In [15]:
df.to_csv(r'C:\Users\chloe\Desktop\City.csv', index=False)